version: '3.8'

services:
  rentalcar:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rentalcar
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://192.168.171.86:1433;database=CarRentalDB;encrypt=true;trustServerCertificate=true;useUnicode=true;characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: sa
    networks:
      default:
        ipv4_address: 192.168.171.86